[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-minimal32
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-minimal32
GtkTheme=oomox-minimal32
IconTheme=oomox-minimal32
MetacityTheme=oomox-minimal32
