#! /usr/bin/bash

HDMI=$(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}')

if [ "$HDMI" == "HDMI-1" ]; then
  xrandr --output HDMI-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1 --mode 1920x1080 --pos 0x1080 --rotate normal
else
  xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
fi