require("min.options")
require("min.plugins")
require("min.telescope")
require("min.gitsigns")
require("min.trouble")
require("min.vimwiki")
require("min.copilot")
-- require("min.completion")
require("min.diagnostic")
require("min.null-ls")
require("min.floating-terminal")
require("min.colorscheme")
require("min.mappings")
require("min.lsp")
require("min.highlights")
require("min.ranger")
require("min.true-zen")
